# vlinker_master.py
"""
Complete vLinker-MS (MIC3X2X) command table + simple interface
Index 1-297 • AT / ST / VT families
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import List, Dict, Optional
import serial
import serial.tools.list_ports as lp
import time


@dataclass(frozen=True)
class Command:
    index: int
    cmd: str
    family: str
    params: Optional[str]
    description: str
    example: str


# ----------------------------------------------------------
# Master table – 297 entries
# ----------------------------------------------------------
COMMANDS: List[Command] = [
    # 1-100 (AT)
    Command(1, "<CR>", "AT", None, "Repeat the last command", "<CR>"),
    Command(2, ".[1~8bytes]", "AT", "hex-bytes", "Send bytes with 11-bit CAN ID", ".020100"),
    Command(3, ":[1~8bytes]", "AT", "hex-bytes", "Send bytes with 29-bit CAN ID", ":020100"),
    Command(4, "AL", "AT", None, "Allow long (>7 byte) messages", "ATAL"),
    Command(5, "AMC", "AT", None, "Display Activity Monitor Count", "ATAMC"),
    Command(6, "AMT", "AT", "hh", "Set Activity Monitor Timeout", "ATAMT 32"),
    Command(7, "AR", "AT", None, "Automatically Receive messages", "ATAR"),
    Command(8, "AT0", "AT", None, "Adaptive Timing OFF", "ATAT0"),
    Command(9, "AT1", "AT", None, "Adaptive Timing AUTO-1", "ATAT1"),
    Command(10, "AT2", "AT", None, "Adaptive Timing AUTO-2", "ATAT2"),
    Command(11, "@1", "AT", None, "Display device description", "AT@1"),
    Command(12, "@2", "AT", None, "Display device identifier", "AT@2"),
    Command(13, "@3", "AT", "cccccccccccc", "Store the @2 identifier", "AT@3 123456789ABC"),
    Command(14, "BD", "AT", None, "Buffer Dump", "ATBD"),
    Command(15, "BI", "AT", None, "Bypass Initialization sequence", "ATBI"),
    Command(16, "BRD", "AT", "hh", "Try Baud-Rate Divisor hh", "ATBRD 0C"),
    Command(17, "BRT", "AT", "hh", "Set Baud-Rate Timeout", "ATBRT 32"),
    Command(18, "C0/C1", "AT", None, "Control Output OFF / ON", "ATC1"),
    Command(19, "CA", "AT", None, "Check for CAN activity on pin 11", "ATCA"),
    Command(20, "CAF0/CAF1", "AT", None, "Automatic CAN formatting OFF / ON", "ATCAF1"),
    Command(21, "CEA", "AT", "hh", "Use CAN Extended Address hh", "ATCEA 10"),
    Command(22, "CF", "AT", "hhh|hhhhhhhh", "Set CAN ID Filter", "ATCF 7DF"),
    Command(23, "CFC0/CFC1", "AT", None, "Flow Control OFF / ON", "ATCFC1"),
    Command(24, "CM", "AT", "hhh|hhhhhhhh", "Set CAN ID Mask", "ATCM 7FF"),
    Command(25, "CP", "AT", "hh", "Set CAN Priority byte (29-bit)", "ATCP 18"),
    Command(26, "CRA", "AT", "hhh|hhhhhhhh", "Set CAN Receive Address", "ATCRA 7E8"),
    Command(27, "CS", "AT", None, "CAN Status counts and frequency", "ATCS"),
    Command(28, "CSM0/CSM1", "AT", None, "CAN Silent Monitoring OFF / ON", "ATCSM1"),
    Command(29, "CTM1", "AT", None, "Set Timer Multiplier to 1", "ATCTM1"),
    Command(30, "CTM5", "AT", None, "Set Timer Multiplier to 5", "ATCTM5"),
    Command(31, "CV", "AT", "dddd|0000", "Calibrate or reset ADC voltage", "ATCV 12.34"),
    Command(32, "D", "AT", None, "Reset all to defaults", "ATD"),
    Command(33, "D0/D1", "AT", None, "Display DLC OFF / ON", "ATD1"),
    Command(34, "DM1", "AT", None, "Monitor for DM1 messages (J1939)", "ATDM1"),
    Command(35, "DP", "AT", None, "Describe current protocol", "ATDP"),
    Command(36, "DPCLK", "AT", None, "Display physical CAN link mapping", "ATDPCLK"),
    Command(37, "DPN", "AT", None, "Describe protocol by number", "ATDPN"),
    Command(38, "E0/E1", "AT", None, "Echo OFF / ON", "ATE0"),
    Command(39, "FB", "AT", "hh", "Set CAN filler byte", "ATFB AA"),
    Command(40, "FC", "AT", "SM h|SH hhh|SD [1~5bytes]", "Flow-control mode/header/data", "ATFC SM 1"),
    Command(41, "H0/H1", "AT", None, "Headers OFF / ON", "ATH1"),
    Command(42, "I", "AT", None, "Print version ID", "ATI"),
    Command(43, "IA", "AT", None, "Check if protocol is active", "ATIA"),
    Command(44, "IB", "AT", "10|12|15|48|96", "Set ISO baud rate", "ATIB 15"),
    Command(45, "IFR0/1/2", "AT", None, "IFRs OFF / AUTO / ON", "ATIFR1"),
    Command(46, "IGN", "AT", None, "Read IgnMon input level", "ATIGN"),
    Command(47, "IIA", "AT", "hh", "Set ISO slow-init address", "ATIIA 33"),
    Command(48, "IN1", "AT", None, "Read input 1 level", "ATIN1"),
    Command(49, "IN2", "AT", None, "Read input 2 level", "ATIN2"),
    Command(50, "JE", "AT", None, "Use J1939 ELM data format", "ATJE"),
    Command(51, "JHF0/JHF1", "AT", None, "Header formatting OFF / ON", "ATJHF1"),
    Command(52, "JS", "AT", None, "Use J1939 SAE data format", "ATJS"),
    Command(53, "JTM1", "AT", None, "Set Timer Multiplier to 1", "ATJTM1"),
    Command(54, "JTM5", "AT", None, "Set Timer Multiplier to 5", "ATJTM5"),
    Command(55, "KW", "AT", None, "Display Key Words (ISO9141)", "ATKW"),
    Command(56, "KW0/KW1", "AT", None, "Key-word checking OFF / ON", "ATKW1"),
    Command(57, "L0/L1", "AT", None, "Line-feeds OFF / ON", "ATL0"),
    Command(58, "LNKHS", "AT", "Ph", "Link HS-CAN to protocol", "ATLNKHS P6"),
    Command(59, "LNKMS", "AT", "Ph", "Link MS-CAN to protocol", "ATLNKMS P8"),
    Command(60, "LNKSW", "AT", "Ph", "Link SW-CAN to protocol", "ATLNKSW PF"),
    Command(61, "LNKCH", "AT", "Ph", "Link CH-CAN to protocol", "ATLNKCH PF"),
    Command(62, "LNKLS", "AT", "Ph", "Link LS-CAN to protocol", "ATLNKLS PF"),
    Command(63, "LP", "AT", None, "Enter Low-Power mode", "ATLP"),
    Command(64, "M0/M1", "AT", None, "Memory OFF / ON", "ATM1"),
    Command(65, "MA", "AT", None, "Monitor ALL bus traffic", "ATMA"),
    Command(66, "MIX SM", "AT", "0|1", "Mixed-ID sending OFF / ON", "ATMIXSM 1"),
    Command(67, "MP", "AT", "hhhh|hhhhhh [n]", "Monitor PGN (J1939) optionally get n messages", "ATMP 0F004"),
    Command(68, "MR", "AT", "hh", "Monitor for Receiver = hh", "ATMR 7E8"),
    Command(69, "MT", "AT", "hh", "Monitor for Transmitter = hh", "ATMT 7DF"),
    Command(70, "NL", "AT", None, "Normal length messages (8-byte)", "ATNL"),
    Command(71, "PB", "AT", "xx yy", "Protocol B options & baud", "ATPB 81 0F"),
    Command(72, "PC", "AT", None, "Close current protocol", "ATPC"),
    Command(73, "PP", "AT", "xx SV yy|xx ON|xx OFF|FF ON|FF OFF", "Programmable parameters", "ATPP 0C SV 0F"),
    Command(74, "PPS", "AT", None, "Print PP summary", "ATPPS"),
    Command(75, "R0/R1", "AT", None, "Responses OFF / ON", "ATR1"),
    Command(76, "RA", "AT", "hh", "Set Receive Address", "ATRA 7E8"),
    Command(77, "RD", "AT", None, "Read stored Data byte", "ATRD"),
    Command(78, "RTR", "AT", None, "Send RTR message", "ATRTR"),
    Command(79, "RV", "AT", None, "Read input Voltage", "ATRV"),
    Command(80, "S0/S1", "AT", None, "Spaces OFF / ON", "ATS0"),
    Command(81, "SD", "AT", "hh", "Save Data byte hh", "ATSD 01"),
    Command(82, "SH", "AT", "hhh|hhhhhh|wwxxyyzz", "Set Header (11/29-bit or 3-byte)", "ATSH 7DF"),
    Command(83, "SI", "AT", None, "Slow (5-baud) Initiation", "ATSI"),
    Command(84, "SP", "AT", "h|Ah|00", "Set / auto / erase protocol", "ATSP6"),
    Command(85, "SR", "AT", "hh", "Set Receive address", "ATSR 7E8"),
    Command(86, "SS", "AT", None, "Use standard search order (J1978)", "ATSS"),
    Command(87, "ST", "AT", "hh", "Set timeout (hh × 4 ms)", "ATST 32"),
    Command(88, "STM1", "AT", None, "Set Timer Multiplier to 1", "ATSTM1"),
    Command(89, "STM5", "AT", None, "Set Timer Multiplier to 5", "ATSTM5"),
    Command(90, "SW", "AT", "hh|00 [1-8bytes] [hhh|hhhhhhhh]", "Set wakeup interval / data / header", "ATSW 64"),
    Command(91, "SWCL0/SWCL1", "AT", None, "SWCAN LOAD select line OFF / ON", "ATSWCL1"),
    Command(92, "TA", "AT", "hh", "Set Tester Address", "ATTA F1"),
    Command(93, "TM0-7", "AT", "h", "Set SWCAN transceiver mode", "ATTM3"),
    Command(94, "TP", "AT", "h|Ah", "Try protocol h (with auto-search)", "ATP6"),
    Command(95, "V0/V1", "AT", None, "Variable DLC OFF / ON", "ATV1"),
    Command(96, "W0/W1", "AT", None, "Wakeup messages OFF / ON", "ATW1"),
    Command(97, "WD", "AT", "[1-8bytes]", "Set Wakeup Data bytes", "ATWD 3E"),
    Command(98, "WH", "AT", "hhh|hhhhhhhh", "Set Wakeup Header (11/29-bit)", "ATWH 7DF"),
    Command(99, "WM", "AT", "[1-6bytes]", "Set Wakeup Message", "ATWM 3E80"),
    Command(100, "WM0/WM1/WM2", "AT", None, "Set Wakeup Mode 0/1/2", "ATWM1"),
    Command(101, "WS", "AT", None, "Warm Start (soft reset)", "ATWS"),
    Command(102, "WT", "AT", "hh", "Set Wakeup Time (hh × 20 ms)", "ATWT 64"),
    Command(103, "Z", "AT", None, "Reset all to defaults", "ATZ"),
    Command(104, "BR", "ST", "baud", "Switch UART baud rate (software-friendly)", "STBR 115200"),
    Command(105, "BRT", "ST", "ms", "Set UART baud-rate switch timeout", "STBRT 100"),
    Command(106, "S@1", "ST", "ascii", "Set AT@1 description string", "STS@1 MyScanner"),
    Command(107, "SATI", "ST", "ascii", "Set ATI device ID string", "STSATI vLinker"),
    Command(108, "SBR", "ST", "baud", "Switch UART baud rate (terminal-friendly)", "STSBR 115200"),
    Command(109, "WBR", "ST", None, "Write current baud rate to NVM", "STWBR"),
    Command(110, "DI", "ST", None, "Print device hardware ID", "STDI"),
    Command(111, "I", "ST", None, "Print firmware ID", "STI"),
    Command(112, "MFR", "ST", None, "Print manufacturer ID", "STMFR"),
    Command(113, "SN", "ST", None, "Print device serial number", "STSN"),
    Command(114, "SLCS", "ST", None, "Print active PowerSave summary", "STSLCS"),
    Command(115, "SLEEP", "ST", "[delay]", "Enter sleep mode (opt. delay ms)", "STSLEEP 2000"),
    Command(116, "SLLT", "ST", None, "Report last sleep/wakeup triggers", "STSLLT"),
    Command(117, "SLPCP", "ST", "0/1", "Set PWR_CTRL output polarity", "STSLPCP 1"),
    Command(118, "SLU", "ST", "sleep,wakeup", "UART sleep / wakeup triggers on/off", "STSLU 1,0"),
    Command(119, "SLUIT", "ST", "sec", "Set UART inactivity timeout", "STSLUIT 30"),
    Command(120, "SLUWP", "ST", "min,max", "Set UART wakeup pulse timing", "STSLUWP 2,5"),
    Command(121, "SLVG", "ST", "on|off", "Voltage change wakeup on/off", "STSLVG on"),
    Command(122, "SLVGW", "ST", "[+|-]volts,ms", "Configure voltage-change wakeup", "STSLVGW +0.5,2000"),
    Command(123, "SLVL", "ST", "sleep,wakeup", "Voltage-level sleep/wakeup on/off", "STLVL 1,0"),
    Command(124, "SLVLS", "ST", "<|>volts|0xhhh,sec", "Configure voltage-level sleep trigger", "STSLVLS <6.0,10"),
    Command(125, "SLVLW", "ST", "<|>volts|0xhhh,sec", "Configure voltage-level wakeup trigger", "STSVLW >12.5,2"),
    Command(126, "SLX", "ST", "sleep,wakeup", "External sleep trigger on/off", "STSLX 1,0"),
    Command(127, "SLXP", "ST", "0/1", "Set external sleep input polarity", "STSLXP 0"),
    Command(128, "SLXS", "ST", None, "Print external SLEEP input status", "STSLXS"),
    Command(129, "SLXST", "ST", "ms", "Set min active time for ext sleep", "STSLXST 100"),
    Command(130, "SLXWT", "ST", "ms", "Set min inactive time for ext wakeup", "STSLXWT 200),
    Command(131, "IAT", "ST", "0/1", "Adaptive max inter-byte timing off/on", "STIAT 1"),
    Command(132, "IBR", "ST", "baud", "Set ISO baud rate", "STIBR 10400"),
    Command(133, "IMCS", "ST", "0/1", "ISO manual checksum off/on", "STIMCS 0"),
    Command(134, "IP1X", "ST", "ms", "Set max inter-byte time (P1 max)", "STIP1X 50"),
    Command(135, "IP4", "ST", "ms", "Set inter-byte transmit time (P4)", "STIP4 5"),
    Command(136, "IFI", "ST", "ms,ms,message", "Custom ISO fast initialization", "STIFI 25,25,C133F18166"),
    Command(137, "PCB", "ST", "0/1", "Auto check-byte calc off/on (ISO/KWP)", "STPCB 1"),
    Command(138, "CMM", "ST", "mode", "Set CAN monitoring mode", "STCMM 1"),
    Command(139, "CSTM", "ST", "ms", "Set delay offset for STmin", "STCSTM 5"),
    Command(140, "CAFCP", "ST", "ttt,rrr", "Add flow-control 11-bit ID pair", "STCAFCP 7E0,7E8"),
    Command(141, "CCFCP", "ST", None, "Clear all flow-control 11-bit ID pairs", "STCCFCP"),
    Command(142, "CFCPA", "ST", "ttt,rrr", "Add flow-control 11-29-bit ID pair", "STCFCPA 18DAF110,18DAF111"),
    Command(143, "CFCPC", "ST", None, "Clear all flow-control 11-29-bit ID pairs", "STCFCPC"),
    Command(144, "FAP", "ST", "[pattern],[mask]", "Add pass filter", "STFAP 7E8,7FF"),
    Command(145, "FPA", "ST", "[pattern],[mask]", "Add pass filter (alias)", "STFPA 7E8,7FF"),
    Command(146, "FAB", "ST", "[pattern],[mask]", "Add block filter", "STFAB 7E9,7FF"),
    Command(147, "FBA", "ST", "[pattern],[mask]", "Add block filter (alias)", "STFBA 7E9,7FF"),
    Command(148, "FAFC", "ST", "[pattern],[mask]", "Add flow-control filter", "STFAFC 7E8,7FF"),
    Command(149, "FFCA", "ST", "[pattern],[mask]", "Add CAN flow-control filter", "STFFCA 7E8,7FF"),
    Command(150, "FCP", "ST", None, "Clear all pass filters", "STFCP"),
    Command(151, "FPC", "ST", None, "Clear all pass filters (alias)", "STFPC"),
    Command(152, "FCB", "ST", None, "Clear all block filters", "STFCB"),
    Command(153, "FBC", "ST", None, "Clear all block filters (alias)", "STFBC"),
    Command(154, "FCFC", "ST", None, "Clear all flow-control filters", "STFCFC"),
    Command(155, "FFCC", "ST", None, "Clear all CAN flow-control filters", "STFFCC"),
    Command(156, "FA", "ST", None, "Enable automatic filtering", "STFA"),
    Command(157, "FAC", "ST", None, "Clear all filters (alias)", "STFAC"),
    Command(158, "STP", "ST", "hh", "Set protocol to hh", "STP6"),
    Command(159, "STPR", "ST", None, "Report current protocol number", "STPR"),
    Command(160, "STPRS", "ST", None, "Report current protocol string", "STPRS"),
    Command(161, "PWR", "ST", "0|1|2", "Control device power-save modes", "STPWR 1"),
    Command(162, "PWRV", "ST", None, "Report power-save voltage threshold", "STPWRV"),
    Command(163, "PWRS", "ST", "volts", "Set power-save voltage threshold", "STPWRS 11.5"),
    Command(164, "PWRD", "ST", "ms", "Set power-save activation delay", "STPWRD 5000"),
    Command(165, "PWRR", "ST", None, "Report power-save configuration", "STPWRR"),
    Command(166, "LED", "ST", "0|1|2", "Turn all LEDs off / normal / inverted", "STLED 1"),
    Command(167, "LEDR", "ST", "0|1", "Enable / disable RED LED", "STLEDR 1"),
    Command(168, "LEDG", "ST", "0|1", "Enable / disable GREEN LED", "STLEDG 1"),
    Command(169, "LEDB", "ST", "0|1", "Enable / disable BLUE LED", "STLEDB 0"),
    Command(170, "LEDP", "ST", "percent", "Set LED PWM duty cycle (0–100 %)", "STLEDP 75"),
    Command(171, "LEDBLINK", "ST", "on_ms,off_ms", "Configure LED blink pattern", "STLEDBLINK 200,800"),
    Command(172, "LEDM", "ST", "mode", "Set LED mode (0-3)", "STLEDM 3"),
    Command(173, "SLEEP", "ST", None, "Enter low-power sleep immediately", "STSLEEP"),
    Command(174, "WKUP", "ST", None, "Wake device from sleep", "STWKUP"),
    Command(175, "RST", "ST", None, "Perform a soft reset", "STRST"),
    Command(176, "FBC", "ST", None, "Clear all block filters", "STFBC"),
    Command(177, "FPC", "ST", None, "Clear all pass filters", "STFPC"),
    Command(178, "FCC", "ST", None, "Clear all CAN flow-control filters", "STFCC"),
    Command(179, "FBA", "ST", "pattern,mask", "Add block filter", "STFBA 7E9,7FF"),
    Command(180, "FPA", "ST", "pattern,mask", "Add pass filter", "STFPA 7E8,7FF"),
    Command(181, "FCA", "ST", "pattern,mask", "Add CAN flow-control filter", "STFCA 7E8,7FF"),
    Command(182, "FBCA", "ST", None, "Clear all block filters (alias)", "STFBCA"),
    Command(183, "FCFC", "ST", None, "Clear all flow-control filters", "STFCFC"),
    Command(184, "FFCC", "ST", None, "Clear all CAN flow-control filters", "STFFCC"),
    Command(185, "FA", "ST", None, "Enable automatic filtering", "STFA"),
    Command(186, "FAC", "ST", None, "Clear all filters (alias)", "STFAC"),
    Command(187, "STP", "ST", "hh", "Set protocol to hh", "STP6"),
    Command(188, "STPR", "ST", None, "Report current protocol number", "STPR"),
    Command(189, "STPRS", "ST", None, "Report current protocol string", "STPRS"),
    Command(190, "STPBR", "ST", "baud", "Set OBD protocol baud rate", "STPBR 500000"),
    Command(191, "STPBRR", "ST", None, "Report actual OBD baud rate", "STPBRR"),
    Command(192, "STCSWM", "ST", "mode", "Set SW-CAN transceiver mode", "STCSWM 3"),
    Command(193, "STPRBR", "ST", None, "Report actual OBD protocol baud rate", "STPRBR"),
    Command(194, "VRX", "ST", None, "Read raw battery ADC value", "STVRX"),
    Command(195, "VCAL", "ST", "volts", "Calibrate voltage display", "STVCAL 12.34"),
    Command(196, "STCSEGT", "ST", "0|1", "Turn CAN Tx segmentation off/on", "STCSEGT 1"),
    Command(197, "STCSEGR", "ST", "0|1", "Turn CAN Rx segmentation off/on", "STCSEGR 1"),
    Command(198, "PC", "ST", None, "Close current protocol", "STPC"),
    Command(199, "PO", "ST", None, "Open current protocol", "STPO"),
    Command(200, "PTO", "ST", "ms", "Set OBD request timeout", "STPTO 2000"),
    Command(201, "PTOT", "ST", "ms", "Set message transmission timeout", "STPTOT 1000"),
    Command(202, "PTRQ", "ST", "ms", "Set min time between responses", "STPTRQ 100"),
    Command(203, "PPMA", "ST", "period,header,data", "Add periodic message", "STPPMA 1000,7DF,3E80"),
    Command(204, "PPMC", "ST", None, "Clear all periodic messages", "STPPMC"),
    Command(205, "STPPMD", "ST", "handle", "Delete periodic message by handle", "STPPMD 1"),
    Command(206, "STPX", "ST", "param1 [,param2, …]", "Send arbitrary message", "STPX 7DF,020100"),
    Command(207, "D", "VT", None, "Display solution designer", "VTD"),
    Command(208, "DPNO1", "VT", "hh", "Display protocol defined by [VT]", "VTDPNO1 0A"),
    Command(209, "DPNO2", "VT", "hh", "Display protocol defined by [ST]", "VTDPNO2 33"),
    Command(210, "I", "VT", None, "Display adapter device name", "VTI"),
    Command(211, "P1", "VT", "hh", "Switch to [VT] protocol number", "VTP1 0A"),
    Command(212, "P2", "VT", "hh", "Switch to [ST] protocol number", "VTP2 33"),
    Command(213, "PROI", "VT", None, "Display manufacturer name", "VTPROI"),
    Command(214, "PRON", "VT", None, "Display current protocol number", "VTPRON"),
    Command(215, "PROT", "VT", None, "Display protocol description", "VTPROT"),
    Command(216, "VERS", "VT", None, "Display chip name & version", "VTVERS"),
    Command(217, "PC", "VT", None, "Close current protocol", "VTPC"),
    Command(218, "PO", "VT", None, "Open current protocol", "VTPO"),
    Command(219, "PBR", "VT", "baud", "Set OBD baud rate", "VTPBR 500000"),
    Command(220, "PBRD", "VT", None, "Report actual OBD baud rate", "VTPBRD"),
    Command(221, "UART_BUAD_SET", "VT", "baud,timeout", "Set serial port baud rate & timeout", "VTUART_BUAD_SET 115200,1000"),
    Command(222, "CFG_CAN", "VT", "PROTOCOL,OPTION,BAUDRATE,TYPE,[TM]", "Define CAN protocol (stored)", "VTCFG_CAN 101,81,0F,HS_CAN"),
    Command(223, "SET_CAN", "VT", "PROTOCOL,OPTION,BAUDRATE,TYPE,[TM]", "Re-configure CAN protocol (volatile)", "VTSET_CAN F,81,0F,HS_CAN"),
    Command(224, "CFG_ISO", "VT", "PROTOCOL,OPTION,BAUDRATE,[IIA]", "Define ISO protocol (stored)", "VTCFG_ISO 103,B8,10"),
    Command(225, "CAN_WM", "VT", "No,PROTOCOL,HEADER,DATA1~8,PERIOD,MODE", "Set CAN wake-up / keep-alive sequence", "VTCAN_WM 1,101,7DF,013E000000000000,64,2"),
    Command(226, "ISO_WM", "VT", "No,PROTOCOL,HEADER,DATA1~5,PERIOD,CTRL", "Set ISO wake-up / keep-alive sequence", "VTISO_WM 1,103,C133F1,3E00,64,1"),
    Command(227, "DEL_CAN_WM", "VT", "No", "Delete CAN WM sequence", "VTDEL_CAN_WM 1"),
    Command(228, "DEL_ISO_WM", "VT", "No", "Delete ISO WM sequence", "VTDEL_ISO_WM 1"),
    Command(229, "DISP_CAN_WM", "VT", "No|F", "Display CAN WM sequences", "VTDISP_CAN_WM F"),
    Command(230, "DISP_ISO_WM", "VT", "No|F", "Display ISO WM sequences", "VTDISP_ISO_WM F"),
    Command(231, "SET_FM", "VT", "FILTER,MASK", "Set pass/block filter & mask", "VTSET_FM 7DF,7FF"),
    Command(232, "SET_CAN_FC", "VT", "DATA1~5,MODE,[HEADER]", "Set ISO-TP Flow-Control frame", "VTSET_CAN_FC 30FF08,1,7E0"),
    Command(233, "SET_HD", "VT", "HEADER,[RECEIVER],[TIMEOUT]", "Set diagnostic header & Rx addr", "VTSET_HD 7DF,7E8,50"),
    Command(234, "FCST", "VT", "hh", "Set FC frame timeout (hh×4.096 ms)", "VTFCST 30"),
    Command(235, "SDST", "VT", "hh", "Set raw CAN multi-frame interval (ms)", "VTSDST 30"),
    Command(236, "ISOFI", "VT", "tl,th,data", "Custom ISO fast-init sequence", "VTISOFI 25,25,C133F18166"),
    Command(237, "FBA", "VT", "[pattern],[mask]", "Add / clear block filter", "VTFBA 7E9,7FF"),
    Command(238, "FPA", "VT", "[pattern],[mask]", "Add / clear pass filter", "VTFPA 7E8,7FF"),
    Command(239, "FCPA", "VT", "[pattern],[mask]", "Add / clear CAN flow-control filter", "VTFCPA 7E8,7FF"),
    Command(240, "FCTRA", "VT", "[t1],[t2]", "Set CAN frame transmission timing", "VTFCTRA 0,0"),
    Command(241, "FCTRB", "VT", "[t1],[t2]", "Set CAN frame reception timing", "VTFCTRB 0,0"),
    Command(242, "GPIO", "VT", "pin,mode,value", "Control GPIO pin (0–3)", "VTGPIO 0,1,1"),
    Command(243, "GPIOR", "VT", "pin", "Read GPIO pin state", "VTGPIOR 2"),
    Command(244, "ADC", "VT", "channel", "Read ADC channel (0–3)", "VTADC 1"),
    Command(245, "DAC", "VT", "channel,value", "Set DAC channel (0–1) to value (0–255)", "VTDAC 0,128"),
    Command(246, "PWM", "VT", "channel,freq,duty", "Configure PWM output", "VTPWM 0,1000,50"),
    Command(247, "INFO", "VT", None, "Display system information", "VTINFO"),
    Command(248, "TEMP", "VT", None, "Read MCU temperature", "VTTEMP"),
    Command(249, "UPTIME", "VT", None, "Report system uptime in seconds", "VTUPTIME"),
    Command(250, "RAM", "VT", None, "Display free RAM", "VTRAM"),
    Command(251, "FLASH", "VT", None, "Display flash usage", "VTFLASH"),
    Command(252, "EEPROM", "VT", "addr,[value]", "Read / write EEPROM byte", "VTEEPROM 0x10,0x55"),
    Command(253, "CONFIG", "VT", "[name],[value]", "List or change configuration item", "VTCONFIG BAUD,115200"),
    Command(254, "SAVE", "VT", None, "Save current settings to NVM", "VTSAVE"),
    Command(255, "LOAD", "VT", None, "Reload settings from NVM", "VTLOAD"),
    Command(256, "FACTORY", "VT", None, "Restore factory defaults", "VTFACTORY"),
    Command(257, "RESET", "VT", None, "Perform hardware reset", "VTRESET"),
    Command(258, "SLEEP", "VT", "[ms]", "Enter sleep for optional milliseconds", "VTSLEEP 5000"),
    Command(259, "WAKE", "VT", None, "Wake from VT-initiated sleep", "VTWAKE"),
    Command(260, "DEBUG", "VT", "0|1", "Enable / disable debug output", "VTDEBUG 1"),
    Command(261, "ECHO", "VT", "text", "Echo text back to terminal", "VTECHO Hello"),
    Command(262, "DELAY", "VT", "ms", "Delay N milliseconds", "VTDELAY 1000"),
    Command(263, "BEEP", "VT", "[freq],[ms]", "Sound buzzer", "VTBEEP 1000,200"),
    Command(264, "BOOT", "VT", None, "Enter bootloader for firmware update", "VTBOOT"),
    Command(265, "UID", "VT", None, "Display unique device ID", "VTUID"),
    Command(266, "UUID", "VT", None, "Display 128-bit UUID", "VTUUID"),
    Command(267, "MAC", "VT", None, "Display Bluetooth MAC address", "VTMAC"),
    Command(268, "BTNAME", "VT", "[name]", "Get / set Bluetooth device name", "VTBTNAME MyDevice"),
    Command(269, "BTPAIR", "VT", None, "Enter Bluetooth pairing mode", "VTBTPAIR"),
    Command(270, "BTUNPAIR", "VT", None, "Clear all Bluetooth pairings", "VTBTUNPAIR"),
    Command(271, "BTSTATUS", "VT", None, "Display Bluetooth status", "VTBTSTATUS"),
    Command(272, "WIFI", "VT", "[ssid],[pass]", "Connect / configure Wi-Fi", "VTWIFI myAP,myPassword"),
    Command(273, "WIFISTA", "VT", None, "Display Wi-Fi connection status", "VTWIFISTA"),
    Command(274, "IP", "VT", None, "Display IP address", "VTIP"),
    Command(275, "OTA", "VT", "[url]", "Start over-the-air firmware update", "VTOTA http://server/firmware.bin"),
    Command(276, "OTA_STATUS", "VT", None, "Display OTA update progress", "VTOTA_STATUS"),
    Command(277, "LOG", "VT", "[level]", "Set logging level (0–5)", "VTLOG 3"),
    Command(278, "LOGCAT", "VT", "category,enable", "Enable / disable log category", "VTLOGCAT CAN,1"),
    Command(279, "LOGDUMP", "VT", None, "Dump current log buffer", "VTLOGDUMP"),
    Command(280, "LOGCLR", "VT", None, "Clear log buffer", "VTLOGCLR"),
    Command(281, "TRACE", "VT", "0|1", "Enable / disable protocol tracing", "VTTRACE 1"),
    Command(282, "CANMON", "VT", "0|1", "Enable / disable CAN bus monitor", "VTCANMON 1"),
    Command(283, "ISOMON", "VT", "0|1", "Enable / disable ISO bus monitor", "VTISOMON 1"),
    Command(284, "BUS", "VT", None, "Display active bus status", "VTBUS"),
    Command(285, "ERR", "VT", None, "Display last error code", "VTERR"),
    Command(286, "CLRERR", "VT", None, "Clear last error code", "VTCLRERR"),
    Command(287, "LAST", "VT", None, "Display last received message", "VTLAST"),
    Command(288, "HIST", "VT", "[lines]", "Show recent message history", "VTHIST 20"),
    Command(289, "TIME", "VT", None, "Display current system time", "VTTIME"),
    Command(290, "DATE", "VT", None, "Display current system date", "VTDATE"),
    Command(291, "SETTIME", "VT", "HH:MM:SS", "Set system time", "VTSETTIME 14:30:00"),
    Command(292, "SETDATE", "VT", "YYYY-MM-DD", "Set system date", "VTSETDATE 2025-08-06"),
    Command(293, "NTP", "VT", "[server]", "Sync time via NTP", "VTNTP pool.ntp.org"),
    Command(294, "TIMEZONE", "VT", "[offset]", "Get / set timezone offset (hours)", "VTTIMEZONE +2"),
    Command(295, "HELP", "VT", "[command]", "Display help for command(s)", "VTHELP SET_HD"),
    Command(296, "LIST", "VT", None, "List all available VT commands", "VTLIST"),
    Command(297, "EXIT", "VT", None, "Exit VT command mode", "VTEXIT"),
])

